# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '30Mart.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(54, 44, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(54, 73, 63, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(54, 102, 85, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 101, 16))
        self.label_5.setObjectName("label_5")
        self.cmbMarke = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMarke.setGeometry(QtCore.QRect(50, 290, 111, 20))
        self.cmbMarke.setObjectName("cmbMarke")
        self.cmbMarke.addItem("")
        self.cmbMarke.addItem("")
        self.cmbMarke.addItem("")
        self.cmbMarke.addItem("")
        self.cmbKategorie = QtWidgets.QComboBox(self.centralwidget)
        self.cmbKategorie.setGeometry(QtCore.QRect(190, 290, 101, 20))
        self.cmbKategorie.setObjectName("cmbKategorie")
        self.cmbKategorie.addItem("")
        self.cmbKategorie.addItem("")
        self.cmbKategorie.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(54, 130, 101, 23))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 270, 66, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 270, 91, 16))
        self.label_7.setObjectName("label_7")
        self.lneCode = QtWidgets.QLineEdit(self.centralwidget)
        self.lneCode.setGeometry(QtCore.QRect(161, 46, 129, 20))
        self.lneCode.setObjectName("lneCode")
        self.lneName = QtWidgets.QLineEdit(self.centralwidget)
        self.lneName.setGeometry(QtCore.QRect(161, 74, 129, 20))
        self.lneName.setObjectName("lneName")
        self.lnePreis = QtWidgets.QLineEdit(self.centralwidget)
        self.lnePreis.setGeometry(QtCore.QRect(161, 102, 129, 20))
        self.lnePreis.setText("")
        self.lnePreis.setObjectName("lnePreis")
        self.lneLager = QtWidgets.QLineEdit(self.centralwidget)
        self.lneLager.setGeometry(QtCore.QRect(161, 130, 129, 20))
        self.lneLager.setText("")
        self.lneLager.setObjectName("lneLager")
        self.lneBschreibung = QtWidgets.QLineEdit(self.centralwidget)
        self.lneBschreibung.setGeometry(QtCore.QRect(50, 200, 241, 71))
        self.lneBschreibung.setText("")
        self.lneBschreibung.setObjectName("lneBschreibung")
        self.tblGros = QtWidgets.QTableWidget(self.centralwidget)
        self.tblGros.setGeometry(QtCore.QRect(310, 40, 741, 271))
        self.tblGros.setRowCount(30)
        self.tblGros.setColumnCount(7)
        self.tblGros.setObjectName("tblGros")
        self.cmbNachKategorie = QtWidgets.QComboBox(self.centralwidget)
        self.cmbNachKategorie.setGeometry(QtCore.QRect(420, 20, 91, 20))
        self.cmbNachKategorie.setObjectName("cmbNachKategorie")
        self.cmbNachKategorie.addItem("")
        self.cmbNachKategorie.addItem("")
        self.cmbNachKategorie.addItem("")
        self.cmbMarke_4 = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMarke_4.setGeometry(QtCore.QRect(700, -249, 91, 20))
        self.cmbMarke_4.setObjectName("cmbMarke_4")
        self.cmbMarke_5 = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMarke_5.setGeometry(QtCore.QRect(926, -293, 91, 20))
        self.cmbMarke_5.setObjectName("cmbMarke_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 20, 111, 16))
        self.label_8.setObjectName("label_8")
        self.btnNachKategorie = QtWidgets.QPushButton(self.centralwidget)
        self.btnNachKategorie.setGeometry(QtCore.QRect(520, 20, 131, 23))
        self.btnNachKategorie.setObjectName("btnNachKategorie")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 320, 741, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnHinzufgen = QtWidgets.QPushButton(self.widget)
        self.btnHinzufgen.setObjectName("btnHinzufgen")
        self.horizontalLayout.addWidget(self.btnHinzufgen)
        self.btnLoschen = QtWidgets.QPushButton(self.widget)
        self.btnLoschen.setObjectName("btnLoschen")
        self.horizontalLayout.addWidget(self.btnLoschen)
        self.btnAktual = QtWidgets.QPushButton(self.widget)
        self.btnAktual.setObjectName("btnAktual")
        self.horizontalLayout.addWidget(self.btnAktual)
        self.btnProduktListe = QtWidgets.QPushButton(self.widget)
        self.btnProduktListe.setObjectName("btnProduktListe")
        self.horizontalLayout.addWidget(self.btnProduktListe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmbMarke.setCurrentIndex(-1)
        self.cmbKategorie.setCurrentIndex(-1)
        self.cmbNachKategorie.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Produktcode"))
        self.label_2.setText(_translate("MainWindow", "Produktname"))
        self.label_3.setText(_translate("MainWindow", "Produktstückpreis"))
        self.label_5.setText(_translate("MainWindow", "Produktbeschreibung"))
        self.cmbMarke.setItemText(0, _translate("MainWindow", "Acer"))
        self.cmbMarke.setItemText(1, _translate("MainWindow", "Samsung"))
        self.cmbMarke.setItemText(2, _translate("MainWindow", "Apple"))
        self.cmbMarke.setItemText(3, _translate("MainWindow", "Oppo"))
        self.cmbKategorie.setItemText(0, _translate("MainWindow", "Telefon"))
        self.cmbKategorie.setItemText(1, _translate("MainWindow", "Computer"))
        self.cmbKategorie.setItemText(2, _translate("MainWindow", "Haushaltsgeräte"))
        self.label_4.setText(_translate("MainWindow", "Produktlagermenge"))
        self.label_6.setText(_translate("MainWindow", "Produktmarke"))
        self.label_7.setText(_translate("MainWindow", "Produktkategorie"))
        self.cmbNachKategorie.setItemText(0, _translate("MainWindow", "Telefon"))
        self.cmbNachKategorie.setItemText(1, _translate("MainWindow", "Computer"))
        self.cmbNachKategorie.setItemText(2, _translate("MainWindow", "Haushaltsgeräte"))
        self.label_8.setText(_translate("MainWindow", "Liste nach Kategorien"))
        self.btnNachKategorie.setText(_translate("MainWindow", "Liste nach Kategorie"))
        self.btnHinzufgen.setText(_translate("MainWindow", "Produkt hinzufügen"))
        self.btnLoschen.setText(_translate("MainWindow", "Produkt löschen"))
        self.btnAktual.setText(_translate("MainWindow", "Produkt aktualisieren"))
        self.btnProduktListe.setText(_translate("MainWindow", "Produktliste"))

